[versions]
agp = "8.2.0"
apiManager = "2.2.4"
kotlin = "2.0.20"
android-minSdk = "24"
android-compileSdk = "34"
kotlinxIoCore = "0.5.4"
kotlinxSerializationJson = "1.7.3"
oshiCore = "6.6.5"

[libraries]
apiManager = { module = "com.github.N7ghtm4r3:APIManager", version.ref = "apiManager" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIoCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshiCore" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }